language: ruby
cache: bundler
bundler_args: --without docs
rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - rbx
  - jruby-9000
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
addons:
   code_climate:
     repo_token: 993125436d81e62150b5b089e19b7d51a677b4f0ce59012b8cc9e17b4d72fb60

